### ISSUE TITLE
Container v1.0 always overwrites tls certificates on restart?

### ISSUE THREAD

**Issue by poVoq** [oragono/oragono-docker#15]
Hi

I am trying to run the official docker image from Dockerhub with Letsencrypt certificates dumped from the Traefik reverse-proxy. I copied over the files to the mounted host directory, but it seems that by default the Docker image creates self-signed certificates and overwrites those in already in the directory.

Here is a log excerpt which happens when I restart the container: 

```
2019-08-24T23:11:41.518Z : info : server : Oragono v1.0.0 exiting
2019/08/24 23:11:43 making self-signed certificates
2019/08/24 23:11:43  making cert for :6697 listener
2019/08/24 23:11:43   Certificate created at certificate.crt : privatekey.key
2019-08-24T23:11:43.104Z : info : server : Oragono v1.0.0 starting
2019-08-24T23:11:43.104Z : info : server : Running commit f396003ec9d7456b747d5a7d71b7893c01b26ef5
2019-08-24T23:11:43.105Z : info : server : Using config file : ircd.yaml
2019-08-24T23:11:43.105Z : info : server : Using MOTD : oragono.motd
2019-08-24T23:11:43.105Z : info : server : Using datastore : ircd.db
2019-08-24T23:11:43.119Z : info : listeners : now listening on :6667, tls=false.
2019-08-24T23:11:43.119Z : info : listeners : now listening on :6697, tls=true.
2019-08-24T23:11:43.120Z : info : server : Server running
```
On non TLS port 6667 everything seems to work, so I think my general setup it ok.

Thanks for the help, and awesome project!

**Comment by DanielOaks** [comment]
Hey @poVoq, thanks for the issue! This is definitely something we should fix up.

What I would do is change the `makecerts` command to stop and ask whether it should overwrite, if it finds existing certificates. Then add two params `--overwrite` (just overwrite the certs) and `--dont-overwrite` (don't overwrite them, just ignore them if they already exist), and have the dockerfile / startup file use `--dont-overwrite`.

I can't promise a timeframe since I'm focused on some other projects right now, but we'll definitely resolve this, sorry for the trouble!

**Comment by slingamn** [comment]
Upon further inspection, I don't agree with the diagnosis here. The current run.sh scripts (in the docker repo) appear to test for existence before running `oragono mkcerts`:

https://github.com/oragono/oragono-docker/blob/32e55247b64a0cffb771c8b1b0060ca10fdc24f7/run.sh#L31

I think a solution at the level of the docker repo is preferable. Maybe we should try debugging the bash script?

**Comment by poVoq** [comment]
Ah, so if I keep the filename as tls.key then it should not overwrite? That would be probably doable for now. Or maybe I just add a fake tls.key ;)

**Comment by DanielOaks** [comment]
~~We could do something like that but it feels like it could be a bit fragile, and we'd probably want to remove the advice in [this section](https://github.com/oragono/oragono-docker#using-custom-tls-certificates) of the readme, since using custom paths would result in... well, very unusual-looking behaviour (deleting the unused `tls.key` / not having that file yet because it's initial-config time results in the completely different keyfile being regenerated, etc). We could have the script either check the files referred to in the config file or something else though, maybe?~~

We could do something else for sure but we'd want to make sure that custom paths can be used without trouble, since the config file allows them and we refer to them in the readme [over here](https://github.com/oragono/oragono-docker#using-custom-tls-certificates). Could we get the bash script or something to pull the paths to those files out of the config? This issue is that the bash file checks for the existence of `tls.key` but the keyfile/certfile could have any name, especially when being copied across from other things like the LE stuff povoq mentions.

**Comment by DanielOaks** [comment]
@poVoq Yeah either having the files named `tls.key` and `tls.crt` or creating fake versions of those files will getcha running for now (good to have both just to make sure however we go with this doesn't re-introduce an unintentional overwrite).

**Comment by poVoq** [comment]
Creating fake versions definitly works. Maybe just add that to the readme for now?

**Comment by slingamn** [comment]
Yeah. I'm not too familiar with docker so I don't completely understand the customization workflow here: what's the standard procedure for maintaining a persistent, customized yaml config and database?

Depending on how the cert workflow works, it seems like this shouldn't come up very much. In particular, shouldn't everything Just Work if you install the LE certificates directly at the paths `/ircd/tls.crt` and `/ircd/tls.key`? It seems like the only way this can arise if if you're installing a custom yaml config with nonstandard cert paths, then executing the standard `run.sh` on container start.

**Comment by slingamn** [comment]
I thought about it a little more and I think here's what I want to do:

1. `oragono mkcerts` should never overwrite certificates; if it detects that certificates are already present, it should fail with an informative error message
1. `run.sh` will run `oragono mkcerts` unconditionally and ignore any errors (`oragono run` will fail if an unexpected issue results in invalid certificates)

**Comment by DanielOaks** [comment]
Sounds good and simple, nice~
