### ISSUE TITLE
Use new multi-stage builds in Docker 17.06

### ISSUE THREAD

**Issue by prologic** [oragono/oragono-docker#2]
See [Docker 17.06 release blog](https://blog.docker.com/2017/06/announcing-docker-17-06-community-edition-ce/)

This will let us ship a slim image that just contains what we need to run oragaono.

**Comment by DanielOaks** [comment]
Interesting, I see. This sounds cool, I'm really interested in this! So basically we make the release on the golang:tip machine and then run it in a very cut-down version of linux that is basically enough to run Oragono and that's it? I'm cool with that.

**Comment by DanielOaks** [comment]
Should we do this now or just make it in a branch and leave it there for now, I'm guessing leave it for at least a few weeks since it's been newly-released. Any clue how long we should wait before taking advantage of new features like this? If we're mostly focused on people running based off DockerHub, would we even need to bother waiting?

**Comment by DanielOaks** [comment]
I think I've got this working fine but my Mac doesn't seem to want to let me use multi-stage builds, have tried both standard and edge builds... Weird

**Comment by prologic** [comment]
I'm going to do this as soon as RancheOS has Docker 17.06 :D

I'm on 17.03 right now though.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by Dreamwalker666** [comment]
I've got this working I had to change to a static build for alpine I have switched to a nginx based image so we can add letsencrypt support next.  

One question though what purpose is the run.sh as you can do it all in the dockerfile?

**Comment by DanielOaks** [comment]
Aha, honestly I'm nowhere near a Docker expert so that's just me stumbling through to get it working somewhat. I'd be happy to do it in the dockerfile instead if we're able.

I'm a little on the fence wrt LE support. If it's not too much work and doesn't add too much tot he filesize then I'm totally cool with adding it though. @Dreamwalker666 would you mind submitting a PR? I've got working multistage stuff on the master+multistage branch for what's it's worth.

Hmm... honestly it might even just be best to just consider looking for a maintainer for this repo and our Docker stuff in general. I'm not really gonna keep that close of an eye on it, just because of my unfamiliarity with it and focusing on the main repo.

**Comment by Dreamwalker666** [comment]
I'll get it working without LE for now I'm not 100% convinced you'd want the container handling it.  Once I sort that i'll do a pull request to this repo.  There isn't that many changes.

Once the dockerfile is working it could just be added to the main repo.   It's just something thats there if you want it.

**Comment by Dreamwalker666** [comment]
oh I am using the master+multistage branch btw :)

**Comment by DanielOaks** [comment]
This is now done by default! Whoo
